version: '3'

services:
  spring-boot-docker:
    image: spring-boot-docker
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 8087:8080
    volumes:
      - /data/spring-boot-docker